### ISSUE TITLE
Service log :- Issues on  new page of detail page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#1001]
![image](https://user-images.githubusercontent.com/79301742/115710165-aba06b00-a38f-11eb-9f11-44da7ebd1f4d.png)

1. labor spell is not matched with add form 
2. description spell is wrong 
3.  background should be there  over the description section 
4. put vendor instead of vendor ID 
5. put asset name instead of asset id 
6. Put Bill# instead of bill number 
7. remove odometer when unit is asset
8.  when we edit and remove and add .. success message label should be same ..

**Comment by rashmi0301** [comment]
DONE

**Comment by rashmi0301** [comment]
@fleetui 
background should be there over the description section

**Comment by rashmi0301** [comment]
After the RND 

CAD currency should be after the price

**Comment by pankaj-fleethawks** [comment]
labor spell is not matched with add form - **already matched in design link**
description spell is wrong - **done on design**
background should be there over the description section - **in design there is already background**
put vendor instead of vendor ID - **done on design**
put asset name instead of asset id - **done on design**
Put Bill# instead of bill number - **done on design**
remove odometer when unit is asset - **it is developing point, so developer do this**
when we edit and remove and add .. success message label should be same - **it is developing point, so developer do this**

check it @rashmi0301 
http://design.fleethawks.com/dashboard/service-log-details.php

**Comment by rashmi0301** [comment]
labor spell is not matched with add form - already matched in design link ---- this should be labor
background should be there over the description section -  -- pending on dev

**Comment by rashmi0301** [comment]
background should be there over the description section - -- pending on dev -- done
