### ISSUE TITLE
Cross Border :- needs to do  Some changes on List view page , Add page  

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#920]
1.  Broker data and broker location is not showing on detail page 
2.  on edit page , asset type is not showing as ew had entered in add form page .
3. Bonded carrier ID is not showing on detail page 
4. put entry type instead of type . Exact data is not showing on detail page 
5. put usa in bond destination title instead of UI destination .proper data ( location ) is not showing on detail view page 
6. put estimated us departure date instead of Estimated Departure Date . Subject to FDA option is not showing -- detail page 
7. third party - type  full name should be show -- detail page 
8. put vehicle name/ number instead of number under the loaded on -- detail page 
9.  Put commodity instead of description -- detail page 
10. quantity unit text style should same . currently all are showing in caps -- detail page 
11. weight , correct units are not showing - detail page 
12. put asset instead of trailer 
13. put hazmat code instead of UN code -- detail page 
14. put contact number instead of contact phone -- detail page 
15. country of origin - full name should show in detail page 
16. C4 line release number -- where it comes from  in detail page 
17. Driver type -- if it is co driver then co driver type should show instead of drivers 
18. driver number is not showing  detail page 
19. put document# instead of travel document # detail page 
20. put actions instead of action in detail page 
21. Driver details -- document type full name should show detail page  
22. put citizenship instead of citizenship country in detail page 
23. put Fast card# instead of fast card number detail page
24. date of birth is not showing detail page 
25. us address details are not showing detail page 
26.  Put issuing province not state and country is missing detail page 

passenger details 

26. put country of citizenship instead of citizenship of country 
27. put Fast card# instead of fast card number detail page
28. Put issuing province not state and country is missing detail page 

truck 

29. In add form -- put vehicle name / number instead of truck number . same as for trailer ( asset) . this should be applicable in detail page also.
30. type name full should appear detail page 
31. dot number where it comes from . and it should be DOT#
32. IIT status where it comes from 

33. Set IIT status button is not working 
34. if we add another shipment , driver , passenger then that respective popup details are not open and showing . 
35. need one step space for all after dots : 
36. IRS number in shipment popup where it comes from -- detail page 
37. put hazardous details title instead of hazmat details 

when we are on edit page 
38. Drivers raw data should not appear 
39. when we shuffle the trailer to truck and truck to trailer then raw data should not show 
40. trips number is not showing 
41. put ace manifest list button in add form page and detail page .. remove actions

**Comment by Hardeep8587** [comment]
Broker data and broker location is not showing on detail page - pending
on edit page , asset type is not showing as ew had entered in add form page 
Bonded carrier ID is not showing on detail page
put entry type instead of type . Exact data is not showing on detail page -  done
put usa in bond destination title instead of UI destination .proper data ( location ) is not showing on detail view page - done
put estimated us departure date instead of Estimated Departure Date - done
Subject to FDA option is not showing -- detail page
third party - type full name should be show -- detail page - done
put vehicle name/ number instead of number under the loaded on -- detail page - loaded on - 
Put commodity instead of description -- detail page - done
quantity unit text style should same . currently all are showing in caps -- detail page - done
weight , correct units are not showing - detail page - done
put asset instead of trailer - done
put hazmat code instead of UN code -- detail page - done
put contact number instead of contact phone -- detail page - done
country of origin - full name should show in detail page - done
C4 line release number -- where it comes from in detail page
Driver type -- if it is co driver then co driver type should show instead of drivers
driver number is not showing detail page - done
put document# instead of travel document # detail page - done
put actions instead of action in detail page - done
Driver details -- document type full name should show detail page - done
put citizenship instead of citizenship country in detail page - done
put Fast card# instead of fast card number detail page - done
date of birth is not showing detail page - done
us address details are not showing detail page
Put issuing province not state and country is missing detail page - done
passenger details

put country of citizenship instead of citizenship of country - done
put Fast card# instead of fast card number detail page - done
Put issuing province not state and country is missing detail page - done
truck

In add form -- put vehicle name / number instead of truck number . same as for trailer ( asset) . this should be applicable in detail page also. - done

type name full should appear detail page - done

dot number where it comes from . and it should be DOT# - from carrier onboard page

IIT status where it comes from - pending

Set IIT status button is not working - done

if we add another shipment , driver , passenger then that respective popup details are not open and showing . - done

need one step space for all after dots :

IRS number in shipment popup where it comes from -- detail page

put hazardous details title instead of hazmat details - done

when we are on edit page
38. Drivers raw data should not appear
39. when we shuffle the trailer to truck and truck to trailer then raw data should not show
40. trips number is not showing - done


few are pending, will move to testing after checking on devapp after merging the branch

**Comment by rashmi0301** [comment]
today i am working on other modules .  ACE is pending only i will check on next working day

**Comment by rashmi0301** [comment]
PENDING 

1. When we are on editing page then asset type (RD) in code is showing 
2. When we are on editing page then fast card is not showing 
3. When we are on editing page then IIT is not showing 

4. US port of arrival - location name is not showing -- Detail page 
5. under the shipment - full address is not showing (Consignor/Consignee) -- detail page 
6. under the shipment - total commodities ( weight is not showing ) and for quantity full name should show -- detail page 
7. Entry Type - Full data is not showing --- detail page 
8. put USA in bond destination title instead of UI destination .proper data ( location ) is not showing on detail view page -- NOT DONE ( code is not showing)
9. Bonded carrier ID is not showing on detail page ---NOT DONE 
10. Subject to FDA option is not showing -- ---NOT DONE  --  detail page 
11. Province of Loading not showing properly -- NOT DONE on detail page 
12. IRS number from where it comes on detail page ?

13. this type of address is showing on detail page ( undefined undefined, Carstairs,Alberta,T0M) under the third party --- NOT DONE 
14.  C4 line release number -- where it comes from  in detail page . when we select the brass options then this option should appear on add form . 
15. Shipment number should be unique if we are having more shipments. error should occur 
15. Driver type -- if it is co driver then co driver type should show instead of drivers -- NOT DONE
16. For different different type only those details are showing . extra should not show . check below screenshot 
![image](https://user-images.githubusercontent.com/79301742/116370126-b6dc1680-a827-11eb-8f65-a619540a4130.png)

17. Goods Astray Date of Exit not showing 
18. driver number is not showing  detail page  
19. us address details are not showing detail page 
20. here is i had entered the location but typed location is not showing and ticked checkbox is showing . check below 
![image](https://user-images.githubusercontent.com/79301742/116505659-134b3e80-a8d9-11eb-8afb-5ecb22750261.png)


passengers 

20. fast card number is not showing 

Vehicle 

21.  IIT status where it comes from  and this is not showing 
22. IIT status is not showing under the asset .

23. send to manifest button functionality is pending 
24. action button is still there 
25.  when reload the detail page then shipment section is not showing . it is appear after sometime 

26. harmonized code should not occur when it is not in add form in particular shipment type 
27. Broker data and broker location is not showing on detail page -- NOT DONE 
28. pagination is not working 
29. please check  all the countries related to the documents . do we need all of the countries related to the particular document .
30. need minus icon when we are having more seal numbers and need space between them

**Comment by rashmi0301** [comment]
4. put entry type instead of type . -- DONE  

6. put estimated us departure date instead of Estimated Departure Date . -- DONE
7. third party - type  full name should be show -- detail page  -- DONE
8. put vehicle name/ number instead of number under the loaded on -- detail page -- DONE
9.  Put commodity instead of description -- detail page -- DONE
10. quantity unit text style should same . currently all are showing in caps -- detail page  -- DONE
11. weight , correct units are not showing - detail page  -- DONE
12. put asset instead of trailer -- DONE
13. put hazmat code instead of UN code -- detail page  -- DONE
14. put contact number instead of contact phone -- detail page  -- DONE
15. country of origin - full name should show in detail page -- DONE


19. put document# instead of travel document # detail page -- DONE
20. put actions instead of action in detail page -- DONE
21. Driver details -- document type full name should show detail page   -- DONE
22. put citizenship instead of citizenship country in detail page -- DONE
23. put Fast card# instead of fast card number detail page -- DONE
24. date of birth is not showing detail page -- DONE

26.  Put issuing province not state and country is missing detail page -- DONE


passenger details 

26. put country of citizenship instead of citizenship of country -- DONE
27. put Fast card# instead of fast card number detail page -- DONE
28. Put issuing province not state and country is missing detail page -- DONE

truck 

29. In add form -- put vehicle name / number instead of truck number . same as for trailer ( asset) . this should be applicable in detail page also. -- DONE
30. type name full should appear detail page -- DONE
31. dot number where it comes from . and it should be DOT# -- DONE

33. Set IIT status button is not working -- REMOVED 
34. if we add another shipment , driver , passenger then that respective popup details are not open and showing . -- DONE
35. need one step space for all after dots : -- DONE

37. put hazardous details title instead of hazmat details -- DONE

when we are on edit page 
38. Drivers raw data should not appear -- DONE
39. when we shuffle the trailer to truck and truck to trailer then raw data should not show -- DONE
40. trips number is not showing -- DONE
41. put ace manifest list button in add form page and detail page ..- DONE
42. Add asset, passenger , co- driver , shipment button is not working --- DONE

**Comment by rashmi0301** [comment]
1. When we are on editing page then asset type (RD) in code is showing -- DONE 
2. When we are on editing page then fast card is not showing -- DONE 
3. When we are on editing page then IIT is not showing --- DONE 

4. US port of arrival - location name is not showing -- Detail page --- DONE 
6. under the shipment - total commodities ( weight is not showing ) and for quantity full name should show -- detail page -- DONE
7. Entry Type - Full data is not showing --- detail page --DONE
8. put USA in bond destination title instead of UI destination .proper data ( location ) is not showing on detail view page -- NOT DONE ( code is not showing)
9. Bonded carrier ID is not showing on detail page ---NOT DONE -- DONE 
11. Province of Loading not showing properly -- NOT DONE on detail page --DONE 
12. IRS number from where it comes on detail page ? -- DONE 

13. this type of address is showing on detail page ( undefined undefined, Carstairs,Alberta,T0M) under the third party --- DONE 


15. Driver type -- if it is co driver then co driver type should show instead of drivers --  DONE
16. For different different type only those details are showing . extra should not show . check below screenshot 
![image](https://user-images.githubusercontent.com/79301742/116370126-b6dc1680-a827-11eb-8f65-a619540a4130.png)

17. Goods Astray Date of Exit not showing -- DONE
18. driver number is not showing  detail page --- DONE 

20. here is i had entered the location but typed location is not showing and ticked checkbox is showing . check below -- DONE 
![image](https://user-images.githubusercontent.com/79301742/116505659-134b3e80-a8d9-11eb-8afb-5ecb22750261.png)


passengers 

20. fast card number is not showing -- done 

Vehicle 

21.  IIT status where it comes from  and this is not showing --DONE
22. IIT status is not showing under the asset .-- done

24. action button is still there -- DONE

26. harmonized code should not occur when it is not in add form in particular shipment type -- DONE
