### ISSUE TITLE
Cross border :- need to add and some items are not showing 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#925]
ACI 

1. If there are two type then need to have comma in between -- listing page 
2. If we have two consignee and consignor then need to have comma in between -- Listing page 
3. Time is not showing -- list page 

Detail view page 

4. Remove actions button 
5. put Canadian port of entry instead of port of entry and name is not showing 
6. put estimated arrival date and time instead of estimated arrival date and time is not
showing properly
7. sub location / warehouse - location name is not showing 
8. Created by --- name is missing 
9. On clicking send to CBSA nothing happens 
10. Quantity and units are not showing as we added in add form 

shipment popup 

11. Put First Canadian Port of Entry instead of Port of Entry and name is not showing 
12. Release office -  name is not showing 
13. Estimated arrival date / time is not showing properly 
14. ETA time zone is not showing 
15. city of loading raw data is appear on add form when we are on editing page 
16. put consignee consignor instead of shipper receiver 
17. state of loading and state of acceptance is not showing 
18. special instruction is not showing 
19. sub location is not showing 
20. Unique Consignment Reference Number is not showing 
21. Importer CSA Business Number is not showing 

Notify party 

22. address is not showing properly . undefined text is showing 

Delivery Destination 

23. address is not showing properly . undefined text is showing 

24. delivery destination details and notify details . please shuffle the position 

Commodities 

25. Put commodity instead of description 
26. Quantity and weight units are not showing properly.
27. handling instruction should show under the commodity details 
28. put Hazardous Material Details instead of hazmat code 
29. Put hazmat code instead of UN code 
30 . Put contact number instead of contact phone 

31. If we click on 2nd shipment then respective data detailed popup is not showing 

Team driver , drivers , passengers 

32. Put main driver , co - driver and passenger instead of Team driver , drivers , passengers 
33. For passenger if we are adding two documents then different different number is not showing .
34. Type should be as co driver , main driver
35. driver number is not showing 
36. put Fast card# instead of fast card number detail page
37. put citizenship instead of citizenship country in detail page
38. date of birth is not showing detail page
39. Driver details -- document type full name should show detail page
40. put document# instead of travel document # detail page
41. Put issuing province not state and country is missing detail page

42.  If we click on 2nd driver  then respective data detailed popup is not showing 

Truck 

43. Cargo exemptions is not showing 
44. put vehicle name / number instead of truck number
45. truck type full name is not showing 
46. put insurance amount instead of policy amount and currency is not showing 
47. insurance company names where it comes from ?
48. Cargo exemptions is not showing 
49. Put VIN/SN instead of VIN 
50. Put vehicle type instead of truck type 
51. Put license province not state and country is missing detail page
52. put seal numbers instead of seals 

Trailers

52. Put asset instead of trailer 
53. put asset type instead of trailer type 
54. put License Plate Number instead of  License Plate
55. put License Province instead of state  & Country is missing 
56. put  IIT or Exemption instead of IIT/Cargo Exemption(s)

Add from of aci 

57. put add asset instead of add trailer button 
58. put plus icon with the add shipment button 
59. loaded on option should change . put vehicle and asset then further asset name / number and vehicle name/number 
60. if we add more seal number then need to have minus icon 
61. container details -- loaded on types should change 
62. co driver raw data is appear 

Container 

63. loaded on data should change . should have vehicle name number .
64. cargo exemptions correct data is not showing 
65. cargo exemption button - what is the function for that ?

66. IIT cargo exemptions data is not showing as we added in add from . 
67. fast card number is not showing when we are on editing page

**Comment by Hardeep8587** [comment]
If there are two type then need to have comma in between -- listing page
If we have two consignee and consignor then need to have comma in between -- Listing page
Time is not showing -- list page
Detail view page

Remove actions button
put Canadian port of entry instead of port of entry and name is not showing - done
put estimated arrival date and time instead of estimated arrival date and time is not
showing properly
sub location / warehouse - location name is not showing
Created by --- name is missing
On clicking send to CBSA nothing happens
Quantity and units are not showing as we added in add form -  done
shipment popup
Put First Canadian Port of Entry instead of Port of Entry and name is not showing
Release office - name is not showing - done
Estimated arrival date / time is not showing properly - done
ETA time zone is not showing - done
city of loading raw data is appear on add form when we are on editing page
put consignee consignor instead of shipper receiver - done
state of loading and state of acceptance is not showing - done
special instruction is not showing
sub location is not showing - done
Unique Consignment Reference Number is not showing
Importer CSA Business Number is not showing
Notify party

address is not showing properly . undefined text is showing
Delivery Destination

address is not showing properly . undefined text is showing

delivery destination details and notify details . please shuffle the position

Commodities

Put commodity instead of description - done

Quantity and weight units are not showing properly. - done

handling instruction should show under the commodity details

put Hazardous Material Details instead of hazmat code - done

Put hazmat code instead of UN code
30 . Put contact number instead of contact phone

If we click on 2nd shipment then respective data detailed popup is not showing

Team driver , drivers , passengers

Put main driver , co - driver and passenger instead of Team driver , drivers , passengers

For passenger if we are adding two documents then different different number is not showing .

Type should be as co driver , main driver

driver number is not showing - done

put Fast card# instead of fast card number detail page - done

put citizenship instead of citizenship country in detail page - done

date of birth is not showing detail page - done

Driver details -- document type full name should show detail page - done

put document# instead of travel document # detail page - done

Put issuing province not state and country is missing detail page - done

If we click on 2nd driver then respective data detailed popup is not showing - done

Truck

Cargo exemptions is not showing
put vehicle name / number instead of truck number 
truck type full name is not showing
put insurance amount instead of policy amount and currency is not showing
insurance company names where it comes from - from vehicle form
Cargo exemptions is not showing - done
Put VIN/SN instead of VIN
Put vehicle type instead of truck type - done
Put license province not state and country is missing detail page - done
put seal numbers instead of seals - done

Trailers
Put asset instead of trailer - done
put asset type instead of trailer type - done
put License Plate Number instead of License Plate - done
put License Province instead of state & Country is missing - done
put IIT or Exemption instead of IIT/Cargo Exemption(s) - done

Add from of aci

put add asset instead of add trailer button - done
put plus icon with the add shipment button - done
loaded on option should change . put vehicle and asset then further asset name / number and vehicle name/number - done
if we add more seal number then need to have minus icon - pending
container details -- loaded on types should change
co driver raw data is appear

Container
loaded on data should change . should have vehicle name number .
cargo exemptions correct data is not showing - done
 
cargo exemption button - what is the function for that ?

IIT cargo exemptions data is not showing as we added in add from .

fast card number is not showing when we are on editing page


WORKING

**Comment by rashmi0301** [comment]
If there are two type then need to have comma in between -- listing page -- PENDING 
If we have two consignee and consignor then need to have comma in between -- Listing page -- PENDING
on editing page - co driver is showing raw data --- PENDING 

Detail view page

4. put Canadian port of entry instead of port of entry and name is not showing --- PENDING .. code is not showing with name 
5. sub location / warehouse - location name is not showing , code is not showing --- PENDING 
6. state is not showing properly and last edited data . check below 
![image](https://user-images.githubusercontent.com/79301742/115669529-fc02d300-a365-11eb-963a-a8744509eec1.png)

7. Put First Canadian Port of Entry instead of Port of Entry and name is not showing --PENDING (Code is not showing )
8. Release office - name is not showing - PENDING (Code is not showing )
9.  state of loading and state of acceptance is not showing --- PENDING ( braw data is showing when we are on editing page )
10. special instruction is not showing --- PENDING 
11. sub location is not showing --- PENDING 
12. Unique Consignment Reference Number is not showing --- PENDING 
13. Importer CSA Business Number is not showing --- PENDING 

Delivery Destination

14. address is not showing properly . undefined text is showing  --- PENDING 
15. state is not showing properly  --- PENDING 
![image](https://user-images.githubusercontent.com/79301742/115670703-56506380-a367-11eb-9049-ef9983cc041a.png)

Notify party

16. address is not showing properly . correct address is not showing that we had added  --- PENDING 

Team driver , drivers , passengers
 
17. Put main driver , co - driver and passenger instead of Team driver , drivers , passengers --- PENDING 
18. when we are editing page of ACI then fast card number is not showing that we had added .  --- PENDING 
19. Type should be as co driver , main driver   --- PENDING 
20.  driver number is not showing   --- PENDING 

Vehicle

21. Cargo exemptions is not showing --- PENDING 
22. In popup -- vehicle type full name is not showing  --- PENDING 
23. Cargo exemptions are not showing  --- PENDING 

24. On clicking the options under the send to CBSA -- on clicking for some nothing happens . and on clicking for some it redirect to edit page

**Comment by Hardeep8587** [comment]
If there are two type then need to have comma in between -- listing page -- Done
If we have two consignee and consignor then need to have comma in between -- Listing page -- done
on editing page - co driver is showing raw data --- Done

Detail view page

put Canadian port of entry instead of port of entry and name is not showing --- Done .. code is not showing with name

sub location / warehouse - location name is not showing , code is not showing --- Sublocation is optional - done

state is not showing properly and last edited data . check below
image

Put First Canadian Port of Entry instead of Port of Entry and name is not showing --done (Code is not showing )

Release office - name is not showing - Done (Code is not showing )

state of loading and state of acceptance is not showing --- Done ( braw data is showing when we are on editing page )

special instruction is not showing --- done

sub location is not showing --- done

Unique Consignment Reference Number is not showing --- done

Importer CSA Business Number is not showing --- done

Delivery Destination

address is not showing properly . undefined text is showing --- done
state is not showing properly --- done
image
Notify party

address is not showing properly . correct address is not showing that we had added --- done
Team driver , drivers , passengers

Put main driver , co - driver and passenger instead of Team driver , drivers , passengers --- Done
when we are editing page of ACI then fast card number is not showing that we had added . --- Done
Type should be as co driver , main driver --- done
driver number is not showing --- Done
Vehicle

Cargo exemptions is not showing --- Done

In popup -- vehicle type full name is not showing --- Done

Cargo exemptions are not showing --- Done

On clicking the options under the send to CBSA -- on clicking for some nothing happens . and on clicking for some it redirect to edit page

**Comment by rashmi0301** [comment]
PENDING 
1. need minus icon when we are having more seal numbers and need space between them
2. On clicking the options under the send to CBSA -- on clicking for some nothing happens . and on clicking for some it redirect to edit page
3. Raw data should not appear when we shuffle the options 
![image](https://user-images.githubusercontent.com/79301742/116506396-cd8f7580-a8da-11eb-8068-d4cfaf334b82.png)

4. pagination is not working
5. please check all the countries related to the documents . do we need all of the countries related to the particular document .
6. Shipment number should be unique if we are having more shipments. error should occur

7. I am not getting the data on detail page .and not able to edit the form now 
![image](https://user-images.githubusercontent.com/79301742/116508307-ad61b580-a8de-11eb-8f00-3041ec2204a9.png)

8 . here is i am typing the location but checked ticked is appear 
![image](https://user-images.githubusercontent.com/79301742/116510701-f3207d00-a8e2-11eb-97b5-89bc3db51f37.png)

9. When we are on editing page then asset type (RD) in code is showing
10. state of loading and state of acceptance is not showing --- ( raw data is showing when we are on editing page )

Delivery Destination/Notify party

11. address is not showing properly . undefined text is showing 
12. please add currency with Insurance Amount 
13. driver number is not showing 
14. Cargo exemptions are not showing

**Comment by rashmi0301** [comment]
DONE POINTS 

If there are two type then need to have comma in between -- listing page -- Done
If we have two consignee and consignor then need to have comma in between -- Listing page -- done
on editing page - co driver is showing raw data --- Done

Detail view page

put Canadian port of entry instead of port of entry and name is not showing . code is not showing with name --- Done .

sub location / warehouse - location name is not showing , code is not showing --- Sublocation is optional  - done

state is not showing properly and last edited data .- done

Put First Canadian Port of Entry instead of Port of Entry and name is not showing --done (Code is not showing )

Release office - name is not showing - Done (Code is not showing )

special instruction is not showing --- done

sub location is not showing --- done

Unique Consignment Reference Number is not showing --- done

Importer CSA Business Number is not showing --- done


Team driver , drivers , passengers

Put main driver , co - driver and passenger instead of Team driver , drivers , passengers --- Done
when we are editing page of ACI then fast card number is not showing that we had added . --- Done
Type should be as co driver , main driver --- done

Vehicle

In popup -- vehicle type full name is not showing --- Done

**Comment by rashmi0301** [comment]
DONE 

1. Raw data should not appear when we shuffle the options
2. When we are on editing page then asset type (RD) in code is showing
3. state of loading and state of acceptance is not showing --- ( raw data is showing when we are on editing page )
4. I am not getting the data on detail page .and not able to edit the form now
5. address is not showing properly . undefined text is showing
7. driver number is not showing

now we are getting all of the data
